dwd_station_url: 'https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/10_minutes/wind_test/historical/'
dwd_station_description: 'zehn_min_ffs_Beschreibung_Stationen.txt'

station_wind_speed_db_name: 'WindData.db'